add_library(engine_lib STATIC)

target_precompile_headers(engine_lib
PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/source/PrecompiledHeaders.hpp
)

target_link_libraries(engine_lib
PUBLIC
    sfml-graphics
    fmt)

target_include_directories(engine_lib
PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/include
PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/source
)

target_sources(engine_lib
 PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Application.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Camera.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/CameraController.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/ChunkedRenderTextureLayer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Context.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/CollisionSolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/FpsCounter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/GameObject.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/debug/ComponentTree.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/keyboard/Utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/layout/Base.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/layout/Constraint.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/layout/Grid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/layout/Horizontal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/layout/Inset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/layout/SizeConstraintResolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/layout/Vertical.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/scrollbar/Base.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/scrollbar/Horizontal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/scrollbar/Vertical.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/Horizontal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/HorizontalMousePolicy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/HorizontalThick.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/HorizontalThickRenderingPolicy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/HorizontalThinRenderingPolicy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/LayoutBuilder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/Vertical.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/VerticalMousePolicy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/VerticalThick.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/VerticalThickRenderingPolicy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/slider/VerticalThinRenderingPolicy.cpp 
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/style/StyleFactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/window/Header.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/window/MenuBar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/window/Panel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/window/StatusBar.cpp

    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Alignment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Application.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/BaseEditBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Button.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Checkbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Clipboard.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/ContextMenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Debug.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/EditBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/EventReceiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/FontHeightCache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/FontLibrary.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/FramedSprite.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/GroupBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/GUI.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Image.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/KeyboardController.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Label.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/ListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/MouseController.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/MultiLineEditBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/ProgressBar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/RadioButton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/RadioButtonGroup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/ScrollView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Selection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Text.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/TextCursor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/TextEnteredController.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Widget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/Window.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/gui/WindowManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/math/Math.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/input/KeyboardHandler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/input/KeyboardReceiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/input/MouseHandler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/input/MouseReceiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/input/TextEnteredReceiver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Logger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/LoggerSink.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Particle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/ParticleSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Profiler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/ProfilingStorage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/RigidBody.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/RigidBodyDebugRenderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Scene.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/Timer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/TimerService.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/TasksQueue.cpp
)
